// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: decent/data/data.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Data struct {
	Address     string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Owner       string `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Network     string `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	DateAdded   uint64 `protobuf:"varint,4,opt,name=dateAdded,proto3" json:"dateAdded,omitempty"`
	DateUpdated uint64 `protobuf:"varint,5,opt,name=dateUpdated,proto3" json:"dateUpdated,omitempty"`
	Method      string `protobuf:"bytes,6,opt,name=method,proto3" json:"method,omitempty"`
	Score       int32  `protobuf:"varint,7,opt,name=score,proto3" json:"score,omitempty"`
	Hit         uint64 `protobuf:"varint,8,opt,name=hit,proto3" json:"hit,omitempty"`
	Uuid        string `protobuf:"bytes,9,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd301fd0c61198bd, []int{0}
}
func (m *Data) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Data.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return m.Size()
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Data) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Data) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *Data) GetDateAdded() uint64 {
	if m != nil {
		return m.DateAdded
	}
	return 0
}

func (m *Data) GetDateUpdated() uint64 {
	if m != nil {
		return m.DateUpdated
	}
	return 0
}

func (m *Data) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Data) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *Data) GetHit() uint64 {
	if m != nil {
		return m.Hit
	}
	return 0
}

func (m *Data) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func init() {
	proto.RegisterType((*Data)(nil), "decent.data.Data")
}

func init() { proto.RegisterFile("decent/data/data.proto", fileDescriptor_bd301fd0c61198bd) }

var fileDescriptor_bd301fd0c61198bd = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x6b, 0x9a, 0xa4, 0xc4, 0x5d, 0xd0, 0x81, 0xaa, 0x1b, 0x90, 0x15, 0x31, 0x65, 0xa1,
	0x0c, 0x3c, 0x01, 0xa8, 0x4f, 0x10, 0x89, 0x85, 0xcd, 0xf4, 0x4e, 0x6a, 0x85, 0x88, 0x23, 0xe7,
	0xaa, 0xc2, 0x5b, 0xf0, 0x58, 0x8c, 0x1d, 0x19, 0x51, 0xc2, 0x83, 0x20, 0xdb, 0x45, 0xb0, 0x9c,
	0xee, 0xfb, 0x7c, 0x3e, 0x9d, 0x7e, 0xbd, 0x20, 0x5e, 0x73, 0x2b, 0x37, 0x64, 0xc5, 0xc6, 0xb2,
	0xec, 0xbc, 0x13, 0x07, 0xf3, 0xe4, 0x97, 0x41, 0x5d, 0x7d, 0x2b, 0x9d, 0xad, 0xac, 0x58, 0x40,
	0x3d, 0xb3, 0x44, 0x9e, 0xfb, 0x1e, 0x55, 0xa5, 0xea, 0xb2, 0xf9, 0x45, 0xb8, 0xd0, 0xb9, 0xdb,
	0xb7, 0xec, 0xf1, 0x24, 0xfa, 0x04, 0x61, 0xbe, 0x65, 0xd9, 0x3b, 0xff, 0x8c, 0xd3, 0x34, 0x7f,
	0x44, 0xb8, 0xd4, 0x25, 0x59, 0xe1, 0x3b, 0x22, 0x26, 0xcc, 0x2a, 0x55, 0x67, 0xcd, 0x9f, 0x80,
	0x4a, 0xcf, 0x03, 0x3c, 0x74, 0xa1, 0x12, 0xe6, 0xf1, 0xfd, 0xbf, 0x82, 0x85, 0x2e, 0x5e, 0x58,
	0x36, 0x8e, 0xb0, 0x88, 0x8b, 0x8f, 0x14, 0xee, 0xe8, 0xd7, 0xce, 0x33, 0xce, 0x2a, 0x55, 0xe7,
	0x4d, 0x02, 0x38, 0xd3, 0xd3, 0xcd, 0x56, 0xf0, 0x34, 0xee, 0x09, 0x2d, 0x80, 0xce, 0x76, 0xbb,
	0x2d, 0x61, 0x19, 0x7f, 0xc7, 0xfe, 0xfe, 0xfa, 0x63, 0x30, 0xea, 0x30, 0x18, 0xf5, 0x35, 0x18,
	0xf5, 0x3e, 0x9a, 0xc9, 0x61, 0x34, 0x93, 0xcf, 0xd1, 0x4c, 0x1e, 0xcf, 0x57, 0x29, 0xa5, 0xd7,
	0x94, 0x93, 0xbc, 0x75, 0xdc, 0x3f, 0x15, 0x31, 0xa9, 0xdb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x08, 0x89, 0x8b, 0xa0, 0x43, 0x01, 0x00, 0x00,
}

func (m *Data) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Data) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Data) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Uuid) > 0 {
		i -= len(m.Uuid)
		copy(dAtA[i:], m.Uuid)
		i = encodeVarintData(dAtA, i, uint64(len(m.Uuid)))
		i--
		dAtA[i] = 0x4a
	}
	if m.Hit != 0 {
		i = encodeVarintData(dAtA, i, uint64(m.Hit))
		i--
		dAtA[i] = 0x40
	}
	if m.Score != 0 {
		i = encodeVarintData(dAtA, i, uint64(m.Score))
		i--
		dAtA[i] = 0x38
	}
	if len(m.Method) > 0 {
		i -= len(m.Method)
		copy(dAtA[i:], m.Method)
		i = encodeVarintData(dAtA, i, uint64(len(m.Method)))
		i--
		dAtA[i] = 0x32
	}
	if m.DateUpdated != 0 {
		i = encodeVarintData(dAtA, i, uint64(m.DateUpdated))
		i--
		dAtA[i] = 0x28
	}
	if m.DateAdded != 0 {
		i = encodeVarintData(dAtA, i, uint64(m.DateAdded))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Network) > 0 {
		i -= len(m.Network)
		copy(dAtA[i:], m.Network)
		i = encodeVarintData(dAtA, i, uint64(len(m.Network)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintData(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintData(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintData(dAtA []byte, offset int, v uint64) int {
	offset -= sovData(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Data) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovData(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovData(uint64(l))
	}
	l = len(m.Network)
	if l > 0 {
		n += 1 + l + sovData(uint64(l))
	}
	if m.DateAdded != 0 {
		n += 1 + sovData(uint64(m.DateAdded))
	}
	if m.DateUpdated != 0 {
		n += 1 + sovData(uint64(m.DateUpdated))
	}
	l = len(m.Method)
	if l > 0 {
		n += 1 + l + sovData(uint64(l))
	}
	if m.Score != 0 {
		n += 1 + sovData(uint64(m.Score))
	}
	if m.Hit != 0 {
		n += 1 + sovData(uint64(m.Hit))
	}
	l = len(m.Uuid)
	if l > 0 {
		n += 1 + l + sovData(uint64(l))
	}
	return n
}

func sovData(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozData(x uint64) (n int) {
	return sovData(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Data) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Data: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Data: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Network", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Network = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DateAdded", wireType)
			}
			m.DateAdded = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DateAdded |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DateUpdated", wireType)
			}
			m.DateUpdated = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DateUpdated |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Method", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Method = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Score", wireType)
			}
			m.Score = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Score |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hit", wireType)
			}
			m.Hit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Hit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uuid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uuid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipData(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipData(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowData
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowData
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowData
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthData
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupData
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthData
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthData        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowData          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupData = fmt.Errorf("proto: unexpected end of group")
)
