version: 1
accounts:
  - name: alice
    coins:
      - 100dhpc
      - 20000token
      - 200000000stake
  - name: bob
    coins:
      - 10000token
      - 100000000stake
  - name: arthur
    coins:
      - 10000token
      - 100000000stake
  - name: carl
    coins:
      - 10000token
      - 100000000stake
  - name: issac
    coins:
      - 10000token
      - 100000000stake
  - name: stan
    coins:
      - 10000token
      - 100000000stake
  - name: andy
    coins:
      - 10000token
      - 100000000stake
  - name: bogh
    coins:
      - 10000token
      - 100000000stake
  - name: oracle
    coins:
      - 100token
      - 100stake
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
    - 100000dhpc
    - 5token
    - 100000stake
validators:
  - name: alice
    bonded: 100000000stake
