// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgWithdrawToken } from "./types/dhpc/user/tx";
import { MsgAddLinkedRequester } from "./types/dhpc/user/tx";
import { MsgRemoveLinkedRequester } from "./types/dhpc/user/tx";
import { MsgDepositToken } from "./types/dhpc/user/tx";

import { LinkedRequesters as typeLinkedRequesters} from "./types"
import { Params as typeParams} from "./types"
import { SlashHistory as typeSlashHistory} from "./types"
import { User as typeUser} from "./types"

export { MsgWithdrawToken, MsgAddLinkedRequester, MsgRemoveLinkedRequester, MsgDepositToken };

type sendMsgWithdrawTokenParams = {
  value: MsgWithdrawToken,
  fee?: StdFee,
  memo?: string
};

type sendMsgAddLinkedRequesterParams = {
  value: MsgAddLinkedRequester,
  fee?: StdFee,
  memo?: string
};

type sendMsgRemoveLinkedRequesterParams = {
  value: MsgRemoveLinkedRequester,
  fee?: StdFee,
  memo?: string
};

type sendMsgDepositTokenParams = {
  value: MsgDepositToken,
  fee?: StdFee,
  memo?: string
};


type msgWithdrawTokenParams = {
  value: MsgWithdrawToken,
};

type msgAddLinkedRequesterParams = {
  value: MsgAddLinkedRequester,
};

type msgRemoveLinkedRequesterParams = {
  value: MsgRemoveLinkedRequester,
};

type msgDepositTokenParams = {
  value: MsgDepositToken,
};


export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgWithdrawToken({ value, fee, memo }: sendMsgWithdrawTokenParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgWithdrawToken: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgWithdrawToken({ value: MsgWithdrawToken.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgWithdrawToken: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgAddLinkedRequester({ value, fee, memo }: sendMsgAddLinkedRequesterParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgAddLinkedRequester: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgAddLinkedRequester({ value: MsgAddLinkedRequester.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgAddLinkedRequester: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgRemoveLinkedRequester({ value, fee, memo }: sendMsgRemoveLinkedRequesterParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgRemoveLinkedRequester: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgRemoveLinkedRequester({ value: MsgRemoveLinkedRequester.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgRemoveLinkedRequester: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgDepositToken({ value, fee, memo }: sendMsgDepositTokenParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgDepositToken: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgDepositToken({ value: MsgDepositToken.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgDepositToken: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgWithdrawToken({ value }: msgWithdrawTokenParams): EncodeObject {
			try {
				return { typeUrl: "/dhpc.user.MsgWithdrawToken", value: MsgWithdrawToken.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgWithdrawToken: Could not create message: ' + e.message)
			}
		},
		
		msgAddLinkedRequester({ value }: msgAddLinkedRequesterParams): EncodeObject {
			try {
				return { typeUrl: "/dhpc.user.MsgAddLinkedRequester", value: MsgAddLinkedRequester.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgAddLinkedRequester: Could not create message: ' + e.message)
			}
		},
		
		msgRemoveLinkedRequester({ value }: msgRemoveLinkedRequesterParams): EncodeObject {
			try {
				return { typeUrl: "/dhpc.user.MsgRemoveLinkedRequester", value: MsgRemoveLinkedRequester.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgRemoveLinkedRequester: Could not create message: ' + e.message)
			}
		},
		
		msgDepositToken({ value }: msgDepositTokenParams): EncodeObject {
			try {
				return { typeUrl: "/dhpc.user.MsgDepositToken", value: MsgDepositToken.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgDepositToken: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						LinkedRequesters: getStructure(typeLinkedRequesters.fromPartial({})),
						Params: getStructure(typeParams.fromPartial({})),
						SlashHistory: getStructure(typeSlashHistory.fromPartial({})),
						User: getStructure(typeUser.fromPartial({})),
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			DhpcUser: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;